
## Bootloader command names, encoded in bytes that can be sent over serial port
## all end with return character
BL_INFO = b'INFO\r'
BL_IMAG = b'IMAG\r'
BL_LOCK = b'LOCK\r'
BL_AKEY = b'AKEY\r'
BL_NKEY = b'NKEY\r'
BL_LICN = b'LICN\r'
BL_EXIT = b'EXIT\r'
BL_CWTS = b'CWTS\r'
BL_MTST = b'MTST\r'
BL_RXEN = b'RXEN\r'
BL_ROFF = b'ROFF\r'
BL_SPIF = b'SPIF\r'
BL_I2CE = b'I2CE\r'
BL_SLEE = b'SLEE\r'
BL_RCAL = b'RCAL\r'
BL_WCAL = b'WCAL\r'
BL_RSER = b'RSER\r'
BL_WSER = b'WSER\r'
BL_CAPA = b'CAPA\r'
